### ISSUE TITLE
How to config many-nodes to work for openpiton?

### ISSUE THREAD

**Issue by zhb9103** [PrincetonUniversity/openpiton#156]
Hi, 
How can I config many-nodes to work for openpiton? And Is it supported by current linux which is ariane-sdk(openpiton branch)?

Thanks!

**Comment by Jbalkind** [comment]
Sorry could you be a little clearer about what you mean by many-nodes? Do you mean multiple chips connected together?

**Comment by zhb9103** [comment]
Yes, I mean multiple chip connected together, as below:
![1](https://github.com/user-attachments/assets/1d156b34-51b9-431c-ac02-7f025ade7dfa)

The "node" concept comes from linux:
![2](https://github.com/user-attachments/assets/519de054-8939-488e-a4b3-fd9740fb49bd)

![3](https://github.com/user-attachments/assets/2415a6c8-c0fd-4d1b-a07b-911813ec0112)
This seems chips connection is configurable

How can I do to impliment chips connection? 

Thanks!

**Comment by Jbalkind** [comment]
Ok two things:
1. The original design relied on Coherence Domain Restriction (Fu et al. MICRO 2015) to enable multi-chip designs. That included ISA-specific components which have not been implemented for RISC-V yet.
2. Instead of using CDR, there is an enhanced design for this use case, SMAPPIC, built by Grigory Chirkov (Chirkov et al. ASPLOS 2023) which can handle multiple chip(let)s including on Amazon F1 FPGAs and is located here: https://github.com/PrincetonUniversity/smappic

You probably want to take a look at SMAPPIC. Note that it is not based on the openpiton git history so it will likely require a little tinkering if you want to take newer patches from OpenPiton and apply them there. SMAPPIC has a lot of great capabilities so I'd definitely recommend you check it out for your purposes.

**Comment by zhb9103** [comment]
Got it. Thanks so much!
